# Generated by Django 3.0.7 on 2020-06-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('tipo_categoria', models.CharField(choices=[('P', 'Produto'), ('S', 'Servico')], max_length=1)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
    ]
